name: First Workflow
on: workflow_dispatch
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps: 
      - name: Print Greeting
        run: echo "Hello Bujji!"
      - name: Print Good bye
        run: echo "Bye Bujji!"
